# Generated by Django 4.2.14 on 2024-07-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_drinkscategory_drinks_drinkscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
