# Generated by Django 4.2.14 on 2024-07-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comments',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reservation_time',
            field=models.DateField(),
        ),
    ]
