# Generated by Django 4.2.14 on 2024-07-26 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_employees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drinks',
            new_name='Drink',
        ),
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
    ]
